export default {
    HOME:'Home',
    CATEGORY:'Category',
    ORDER:'Order',
    VIEW_ORDER:'View_Order',
    CART:'CART',
    ACCOUNT:'Account',
    LOGIN:'Login',
    REGISTER: 'Register',
    TAB_ROUTE:'Tab_Route',
    SUB_CATEGORY:'Sub_Category',
    PRODUCT_INFO:'ProductInfo',
    SEARCH_SCREEN:'Search_Screen',
    SEARCH_RESULT:'Search_Result',
    CHECKOUT:'Checkout',
    ORDER_COMPLETED:'Order_Completed',
    OTP_SCREEN:'OTP_Screen',
    SEND_ENQUIRY:'Send_Enquiry',
    EDIT_PROFILE:'Edit_Profile',
    NEW_ARRIVALS:'New_Arrivals',
}