export default {
    STATE:[
        'andaman and nicobar',
        'andhra pradesh',
        'arunachal pradesh',
        'assam',
        'bihar',
        'chhattisgarh',
        'chandigarh',
        'daman',
        'delhi',
        'goa',
        'gujarat',
        'haryana',
        'himachal pradesh',
        'jammu and kashmir',
        'jharkhand',
        'karnataka',
        'kerala',
        'ladakh',
        'lakshadweep',
        'madhya pradesh',
        'maharashtra',
        'manipur',
        'meghalaya',
        'mizoram',
        'nagaland',
        'odisha',
        'puducherry',
        'punjab',
        'rajasthan',
        'sikkim',
        'tamil nadu',
        'telangana',
        'tripura',
        'uttar pradesh',
        'uttarakhand',
        'west bengal',
    ]
}